#440 Reproducibility and Statistics Assignment

 
```{r}
pols<-read.csv("politics.csv")
```



```{r}
str(pols)
```


```{r}
pols$subject<-factor(pols$subject)
pols$testtime<-factor(pols$testtime, levels=c("pre", "post"))
```




```{r}
summary(pols$income)
```


  

```{r}
hist(pols$income[pols$testtime=="post"])
```




```{r}
tab<-table(pols$party[pols$testtime=="pre"],pols$minwage[pols$testtime=="pre"])
tab
```



```{r}
chisq.test(pols$party[pols$testtime=="pre"],pols$minwage[pols$testtime=="pre"])
```




  

```{r}
t.test(pols$optimism[pols$sex=="male" & pols$testtime=="pre"],pols$optimism[pols$sex=="female" & pols$testtime=="pre"])
```




```{r}
library("dplyr")
temp<-pols[pols$testtime=="pre",]%>%group_by(sex)%>%summarize(means=mean(optimismscore),
                                                              sems=sd(optimismscore)/sqrt(length(optimismscore)))
library("ggplot2")
f<-ggplot(temp,aes(x=factor(sex),y=means))+
  geom_bar(stat="identity", color="black",fill=c("deeppink","deepskyblue2"))+
  geom_errorbar(aes(ymax=means+sems, ymin=means-sems), width=.1)
f
```



```{r}
f<-f+ggtitle("Video Optimism Scores by Sex")+
labs(x="Sex", y="Pretest Optimism Scores\n(higher=more optimistic")+
scale_x_discrete(breaks=c("female","male"),labels=c("Female","Male"))+
theme(plot.title=element_text(size=15,face="bold",vjust=.5))+
theme(axis.title.x=element_text(size=12,face="bold",vjust=-.25))+
theme(axis.title.y=element_text(size=12,face="bold",vjust=1))+
theme(axis.text.x=element_text(size=10,face="bold",color="black"))+
theme(axis.text.y=element_text(size=10,face="bold",color="black"))+
coord_cartesian(ylim=c(min(temp$means)-2*max(temp$sems),max(temp$means)+2*max(temp$sems)))+
theme(panel.border=element_blank(), axis.line=element_line())+
theme(panel.grid.major.x=element_blank())+
theme(panel.grid.major.y=element_line(color="darkgrey"))+
theme(panel.grid.minor.y=element_blank())
f
```




```{r}
summary(aov(income~party*sex,data=pols[pols$testtime=="pre",]))
```



```{r}
temp<-pols[pols$testtime=="pre",]%>%group_by(party,sex)%>%
summarize(means=mean(income),sems=sd(income)/sqrt(length(income)))
library("gplots")
col1=col2hex("deeppink")
col2=col2hex("deepskyblue2")
f<-ggplot(temp, aes(x=party, y=means, fill=sex))+
geom_bar(stat="identity",position=position_dodge())+
scale_fill_manual(values=c(col1,col2),name="Sex",breaks=c("female","male"),labels=c("Female", "Male"))+
theme(legend.key=element_rect(color="black"))+
geom_errorbar(aes(ymax=means+sems, ymin=means-sems),width=.2,position=position_dodge(.9))+
ggtitle("Incomes by Sex and Political Affiliation")+
labs(x="Political Party Affiliation",y="Income\n(thousands of dollars)")+
scale_x_discrete(breaks=c("democrat","independent","republican"),labels=c("Democrat","Independent","Republican"))+
theme(plot.title=element_text(size=15,face="bold",vjust=.5))+
theme(axis.title.x=element_text(size=12,face="bold",vjust=-.25))+
theme(axis.title.y=element_text(size=12,face="bold",vjust=1))+
theme(axis.text.x=element_text(size=10,face="bold",color="black"))+
theme(axis.text.y=element_text(size=10,face="bold",color="black"))+
coord_cartesian(ylim=c(min(temp$means)-2*max(temp$sems),max(temp$means)+2*max(temp$sems)))+
theme(panel.border=element_blank(),axis.line=element_line())+
theme(panel.grid.major.x=element_blank())+
theme(panel.grid.major.y=element_line(color="darkgrey"))+
theme(panel.grid.minor.y=element_blank())+
theme(legend.position=c(.2,.76))+
theme(legend.background=element_blank())+
theme(legend.background=element_rect(color="black"))+
theme(legend.title=element_blank())+
theme(legend.title=element_text(size=12))+
theme(legend.title.align=.5)+
theme(legend.text=element_text(size=10,face="bold"))
f
```





  ```{r}
f<-ggplot(temp, aes(x=party, y=means, group=sex, color=sex))+
  geom_line(size=1)+
  geom_point(size=2)+
  scale_color_manual(values=c(col1,col2),name="Sex",breaks=c("female","male"),labels=c("Female", "Male"))+
  geom_errorbar(aes(ymax=means+sems, ymin=means-sems),width=.2)+
  ggtitle("Incomes by Sex and Political Affiliation")+
  labs(x="Political Party Affiliation",y="Income\n(thousands of dollars)")+
  scale_x_discrete(breaks=c("democrat","independent","republican"),labels=c("Democrat","Independent","Republican"))+
  theme(plot.title=element_text(size=15,face="bold",vjust=.5))+
  theme(axis.title.x=element_text(size=12,face="bold",vjust=-.25))+
  theme(axis.title.y=element_text(size=12,face="bold",vjust=1))+
  theme(axis.text.x=element_text(size=10,face="bold",color="black"))+
  theme(axis.text.y=element_text(size=10,face="bold",color="black"))+
  coord_cartesian(ylim=c(min(temp$means)-2*max(temp$sems),max(temp$means)+2*max(temp$sems)))+
  theme(panel.border=element_blank(),axis.line=element_line())+
  theme(panel.grid.major.x=element_blank())+
  theme(panel.grid.major.y=element_line(color="darkgrey"))+
  theme(panel.grid.minor.y=element_blank())+
  theme(legend.position=c(.2,.76))+
  theme(legend.background=element_blank())+
  theme(legend.background=element_rect(color="black"))+
  theme(legend.title=element_blank())+
  theme(legend.title=element_text(size=12))+
  theme(legend.title.align=.5)+
  theme(legend.text=element_text(size=10,face="bold"))
f
```


  
 

```{r}
summary(aov(optimismscore~testtime*party+Error(subject/testtime),data=pols))
```



```{r}
summary(lm(optimismscore~income+sex,data=pols[pols$testtime=="pre",]))
```

```{r}
f<-ggplot(pols[pols$testtime=="pre",],aes(x=income,y=optimismscore,color=sex))+
geom_point(size=2)+
geom_abline(intercept=60.2+2.51/2, slope=-.092,color=col1)+
geom_abline(intercept=60.2-2.51/2, slope=-.092,color=col2)+
scale_color_manual(values=c(col1,col2),breaks=c("female","male"),labels=c("Female","Male"))+
ggtitle("Optimism Predicted by Sex and Income")+
labs(x="Income (Thousands of Dollars)",y="Optimism Score\n(Higher=More)")+
theme(plot.title=element_text(size=15,face="bold", vjust=.5))+
theme(axis.title.x=element_text(size=12,face="bold", vjust=-.25))+
theme(axis.title.y=element_text(size=12,face="bold", vjust=1))+
theme(axis.text.x=element_text(size=10,face="bold",color="black"))+
theme(axis.text.y=element_text(size=10,face="bold",color="black"))+
theme(panel.border=element_blank(), axis.line=element_line())+
theme(panel.grid.major.x=element_blank())+
theme(panel.grid.minor.x=element_blank())+
theme(panel.grid.major.y=element_line(color="darkgrey"))+
theme(panel.grid.minor.y=element_blank())+
theme(legend.position=c(.83,.86))+
theme(legend.background=element_blank())+
theme(legend.title=element_blank())+
theme(legend.text=element_text(size=10,face="bold"))
f
```

